version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: dvwa-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: passward
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    restart: unless-stopped
    environment:
      - DB_SERVER=db
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=dvwa
    depends_on:
      - db
    # Don’t expose DVWA directly to the host; let the proxy handle it
    expose:
      - "80"

  reverse-proxy:
    build: ./reverse-proxy
    container_name: apache-proxy
    restart: unless-stopped
    depends_on:
      - dvwa
    ports:
      - "443:443"

volumes:
  db_data:
