version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80" #in case port 80 is being used by something else
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=dvwa
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: dvwa_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dvwa
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
